/**
 * Regenerates cintexa-nexus-standalone/ from the current source of truth
 * (lib/db schema, scripts/src/seed.ts, artifacts/api-server, artifacts/cintexa-nexus).
 *
 * Run this any time the DB schema, seed data, server code, or frontend
 * changes and you want the Windows/npm standalone package to stay in sync.
 * Never hand-edit generated files inside cintexa-nexus-standalone/scripts/
 * or cintexa-nexus-standalone/server/ — they are overwritten here.
 *
 * Usage:  pnpm --filter @workspace/scripts run build-standalone
 */
import { build as esbuild } from "esbuild";
import { execSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..", "..");

const dbDir = path.join(root, "lib", "db");
const apiServerDir = path.join(root, "artifacts", "api-server");
const frontendDir = path.join(root, "artifacts", "cintexa-nexus");
const standaloneDir = path.join(root, "cintexa-nexus-standalone");

function step(label: string, fn: () => void) {
  console.log(`\n▶ ${label}`);
  fn();
  console.log(`✅  ${label}`);
}

// ── 1. Sync DB migrations ──────────────────────────────────────────────────
step("Sync DB migrations from lib/db/drizzle", () => {
  const srcDir = path.join(dbDir, "drizzle");
  const destDir = path.join(standaloneDir, "scripts", "migrations");
  rmSync(destDir, { recursive: true, force: true });
  mkdirSync(destDir, { recursive: true });
  const sqlFiles = readdirSync(srcDir).filter((f) => f.endsWith(".sql"));
  if (sqlFiles.length === 0) {
    throw new Error(
      `No .sql migration files found in ${srcDir}. Run 'pnpm --filter @workspace/db run push' (or drizzle-kit generate) first.`,
    );
  }
  for (const file of sqlFiles) {
    cpSync(path.join(srcDir, file), path.join(destDir, file));
  }
  console.log(`   copied ${sqlFiles.length} migration file(s)`);
});

// ── 2. Bundle the seed script straight from scripts/src/seed.ts ───────────
step("Bundle scripts/src/seed.ts -> cintexa-nexus-standalone/scripts/seed.mjs", async () => {
  await esbuild({
    entryPoints: [path.join(root, "scripts", "src", "seed.ts")],
    outfile: path.join(standaloneDir, "scripts", "seed.mjs"),
    platform: "node",
    bundle: true,
    format: "esm",
    logLevel: "info",
    external: ["pg"],
    banner: {
      js: `// AUTO-GENERATED by 'pnpm --filter @workspace/scripts run build-standalone' from scripts/src/seed.ts. Do not hand-edit.
import { createRequire as __bannerCrReq } from 'node:module';
globalThis.require = __bannerCrReq(import.meta.url);
`,
    },
  });
});

// ── 3. Build the server bundle (existing esbuild pipeline) ────────────────
step("Build api-server standalone bundle", () => {
  execSync("node build-standalone.mjs", { cwd: apiServerDir, stdio: "inherit" });
});

// ── 4. Build the frontend (static, relative-path build) ───────────────────
step("Build frontend standalone bundle", () => {
  execSync("pnpm run build:standalone", { cwd: frontendDir, stdio: "inherit" });
});

// ── 5. Copy built server + frontend into the standalone package ───────────
step("Copy build output into cintexa-nexus-standalone/server", () => {
  const serverDestDir = path.join(standaloneDir, "server");
  const publicDestDir = path.join(serverDestDir, "public");

  // Server bundle (keep server/public across the wipe)
  const serverSrcDir = path.join(apiServerDir, "standalone-dist");
  for (const file of readdirSync(serverSrcDir)) {
    if (existsSync(path.join(serverDestDir, file))) {
      rmSync(path.join(serverDestDir, file), { recursive: true, force: true });
    }
    cpSync(path.join(serverSrcDir, file), path.join(serverDestDir, file), {
      recursive: true,
    });
  }

  // Frontend static bundle
  rmSync(publicDestDir, { recursive: true, force: true });
  mkdirSync(publicDestDir, { recursive: true });
  cpSync(path.join(frontendDir, "dist-standalone"), publicDestDir, {
    recursive: true,
  });
});

console.log("\n✅  cintexa-nexus-standalone/ is now in sync with the main app.");
console.log("   Re-zip it (or re-run this script) whenever the schema, seed data, server, or frontend change.");
